### ISSUE TITLE
Parse module? 

### ISSUE THREAD

**Issue by bengoehring** [ripl-org/sockit#4]
Hi there,

Thanks for a great package. Is the parse functionality available as a module or just a command line tool? The wiki suggests the latter (in contrast to the title functionality). 

Apologies if the question is silly -- I work almost exclusively in R so this is a bit of foreign ground for me.

**Comment by m-goggins** [comment]
@bengoehring Yes, there is!

1. Install sockit via command line: `pip install sockit`
2. In your python script, import the relevant packages from the[ __init__.py file](https://github.com/ripl-org/sockit/blob/main/sockit/parse/__init__.py) for the parse function, e.g.:  `from sockit.parse import parse_job_posting`
3. In your python script, use your imported package, e.g.: `results = parse_job_posting(filename="path/to/job/posting")`

Hope this is helpful!

**Comment by bengoehring** [comment]
Got it -- thank you!
